services:
  ai-services:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8001:8001"
    volumes:
      - ./:/app
      - hf_cache:/root/.cache/huggingface
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload

volumes:
  hf_cache: